Repository chipsalliance/sv-tests, pull requests merged in 2019-08, with the labels that each got.

#3 tests: fix the sanity-check test tags
  tests/sanity.sv
Labels: bug

#5 Make odin wrapper work without external XML files
  README.md
  runners/odin
Labels: enhancement

#2 Make the report generator extensible
  conf/report-template.html
  tools/sv-report
Labels: enhancement

#6 report: show logs upon clicking results cell
  conf/report-template.html
  tools/sv-report
Labels: enhancement

#7 report: styling improvements
  conf/report-template.html
Labels: enhancement

#9 Improve Makefile target generation performance
  Makefile
  tools/runner
Labels: enhancement

#14 Tabs for logfiles
  conf/report-template.html
  tools/sv-report
Labels: enhancement, report

#16 report: trim redundant whitespace in the generated file
  tools/sv-report
Labels: enhancement, report

#15 explicitly mark features with varied results
  conf/report-template.html
  tools/sv-report
Labels: dependent, report

#17 highlight the currently selected cell
  conf/report-template.html
Labels: enhancement, report

#18 Make the makefile output more verbose
  Makefile
  tools/runner
  tools/sv-report
Labels: enhancement

#23 Hide yosys banners
  runners/yosys
Labels: runners

#24 verilator: don't fail because of warnings
  runners/verilator
Labels: runners

#25 tools: fix issue with tests erroneously being logged as failed
  tools/runner
Labels: bug

#30 Add names to the tags in the report
  conf/report-template.html
Labels: enhancement, report

#28 Show more details in the report cells
  conf/report-template.html
  tools/sv-report
Labels: enhancement, report

#27 Improve the log file tabs in the report
  conf/report-template.html
Labels: bug, report

#31 Allow the tests to be in subdirectories
  Makefile
  conf/report-template.html
  tools/sv-report
Labels: enhancement, tests

#39 Add initial travis config
  .travis.yml
  conf/requirements.txt
Labels: enhancement

#42 ci: deploy report using github pages
  .travis.yml
Labels: dependent
