Repository chipsalliance/sv-tests, pull requests merged in 2020-12, with the labels that each got.

#1183 Include the actual test code in path-generator tests
  generators/path_generator
Labels: bug, tests

#1184 Blacklist hdlconvertor tests that are not legal.
  conf/generators/meta-path/hdlconvertor.json
Labels: merge-if-green

#1228 Add defines support to sv_parser
  tools/runners/sv_parser.py
Labels: kokoro:force-run
